import type {Encoding} from './conversion/engine';
// Small, standards-compliant uncompressed ZIP writer. UTF-8, CRC32 and central directory.
export function zip(files:Record<string,string>):Uint8Array {
 const enc=new TextEncoder(),parts:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;
 const u16=(v:DataView,o:number,n:number)=>v.setUint16(o,n,true),u32=(v:DataView,o:number,n:number)=>v.setUint32(o,n,true);
 for(const [path,text] of Object.entries(files)){const name=enc.encode(path),data=enc.encode(text);let crc=0xffffffff;for(const b of data){crc^=b;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}crc=(crc^0xffffffff)>>>0;
 const local=new Uint8Array(30+name.length),v=new DataView(local.buffer);u32(v,0,0x04034b50);u16(v,4,20);u16(v,6,0x800);u32(v,14,crc);u32(v,18,data.length);u32(v,22,data.length);u16(v,26,name.length);local.set(name,30);
 const c=new Uint8Array(46+name.length),w=new DataView(c.buffer);u32(w,0,0x02014b50);u16(w,4,20);u16(w,6,20);u16(w,8,0x800);u32(w,16,crc);u32(w,20,data.length);u32(w,24,data.length);u16(w,28,name.length);u32(w,42,offset);c.set(name,46);central.push(c);parts.push(local,data);offset+=local.length+data.length;
 }const size=central.reduce((n,b)=>n+b.length,0),end=new Uint8Array(22),e=new DataView(end.buffer);u32(e,0,0x06054b50);u16(e,8,central.length);u16(e,10,central.length);u32(e,12,size);u32(e,16,offset);parts.push(...central,end);const out=new Uint8Array(offset+size+22);let pos=0;for(const p of parts){out.set(p,pos);pos+=p.length;}return out;
}
const escape=(s:string)=>s.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!)).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'');
export function wordBytes(text:string,font:Encoding){if(!text)throw Error('Empty result');const fontName={krutidev:'Kruti Dev 010',devlys:'DevLys 010',chanakya:'Chanakya',preeti:'Preeti',mangal:'Mangal',unicode:'Nirmala UI'}[font];const body=text.replace(/\r\n?/g,'\n').split('\n').map(line=>`<w:p><w:r><w:rPr><w:rFonts w:ascii="${fontName}" w:hAnsi="${fontName}" w:cs="${fontName}"/><w:sz w:val="24"/></w:rPr>${line.split('\t').map(part=>`<w:t xml:space="preserve">${escape(part)}</w:t>`).join('<w:tab/>')}</w:r></w:p>`).join('');return zip({'[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>','_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>','word/document.xml':`<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr/></w:body></w:document>`});}
export async function downloadWord(text:string,font:Encoding){const data=wordBytes(text,font),url=URL.createObjectURL(new Blob([data as BlobPart],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}));const a=document.createElement('a');a.href=url;a.download=`akshar-${font}.docx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
